config/routes.rb
Rails.application.routes.draw do
get 'todos', to: 'todos#index'
get 'todos/new'
post 'todos', to: 'todos#create'
get 'todos/:id', to: 'todos#show', as: 'todo'
get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
patch 'todos/:id', to: 'todos#update'
delete 'todos/:id', to: 'todos#destroy'
post 'complete/:id', to: 'complete#create', as: 'complete'
get 'complete/list', to: 'complete#list'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/complete_controller.rb
class CompleteController < ApplicationController
  
def update
  @todo = Todo.find(params[:id])
  if @todo.complete?
    @todo.save
    redirect_to todos_path, notice: 'ToDo added to List'
  else
    @todo.complete = false
    @todo.save
    redirect_to todos_path, notice: 'ToDo removed from List'
  end

  def list
    @todos = Todo.all
  end
end

private

  def movie_params
    params.require(:todo).permit(:description, :completed)
  end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
before_action :set_todo, only: %i[show edit update destroy]


def index
  @todos = Todo.all
end

def new
  @todo = Todo.new
end

def create
  @todo = Todo.create(todo_params)
  redirect_to todos_path
end

def show; end

def edit; end

def update
  @todo.update(todo_params)
redirect_to todos_path
end

def destroy
  @todo.destroy
  redirect_to todos_path
end

end

private

  def todo_params
    params.require(:todo).permit(:description, :completed)
  end

  def set_todo
      @todo = Todo.find(params[:id])
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complete_helper.rb
module CompleteHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark text-white btn mb-5">
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item ml-5">
            <a <%= link_to "Index", todos_path %></a>
            </li>
            <li class="nav-item ml-5">
              <a <%= link_to "List", complete_list_path %></a>
            </li>
            <li class="nav-item ml-5">
              <a <%= link_to "Create ToDo", todos_new_path %></a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
          <button class="btn btn-outline-white my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <%= notice %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="row align-middle">
<%= form_with model: @todo, local: true do |todo| %>
<br>
<div class="col-md-4 text-left">
<%= todo.label :description %>
<%= todo.text_field :description %>
</div>
<div class="col-md-4 text-left">
<%= todo.label :completed %>
<%= todo.check_box :completed, id: :completed %>
</div>
<%= todo.submit class:'btn' %>

<% end %>

</div>

app/views/todos/edit.html.erb
<h1>Edit ToDo</h1>

<%= render "form", todo: @todo %>

app/views/todos/index.html.erb
<div class="container">
<h1>My ToDos</h1>
<br>
<h3>Completed ToDos</h3>
<% @todos.each do |todo| %>
<p><%= "#{todo.description} /  #{todo.completed}" %></p>
<div class="card-columns">
  <div class="card text-center">
    <div class="card-body">
      <h5 class="card-text"><%= todo.description %></h5>
      <p class="card-text"><%= todo.completed %></p>
    </div>
  </div>
</div>

<p><%= link_to 'Show', todo, class:'btn btn-sm' %>
<%= link_to 'Edit ToDo', edit_todo_path(todo), class:'btn btn-sm' %>
<%= link_to 'Delete ToDo', todo, method: :delete, data: { confirm: 'Are you sure about this?'}, class: 'btn btn-sm' %>
<%= button_to 'Complete', complete_path(todo), method: :patch, class:'btn-warning btn-sm' %></p>
<% end %>

<h3>Incompleted ToDos</h3>
<% @todos.each do |todo| %>
<p><%= "#{todo.description} /  #{todo.completed}" %></p>
<div class="card-columns">
  <div class="card text-center">
    <div class="card-body">
      <h5 class="card-text"><%= todo.description %></h5>
      <p class="card-text"><%= todo.completed %></p>
    </div>
  </div>
</div>

<p><%= link_to 'Show', todo, class:'btn btn-sm' %>
<%= link_to 'Edit ToDo', edit_todo_path(todo), class:'btn btn-sm' %>
<%= link_to 'Delete ToDo', todo, method: :delete, data: { confirm: 'Are you sure about this?'}, class: 'btn btn-sm' %>
<%= button_to 'Incomplete', complete_path(todo), method: :patch, class:'btn-danger btn-sm' %></p>

<br>
<%= link_to 'Create ToDo', todos_new_path, class:'btn btn-sm' %>

<% end %>
</div>

app/views/todos/list.html.erb
<div class="row align-items-center">

<div class="col-md-6 btn">
  <div class="text-white align-items-center text-center justify-content-center">
    <div class="pt-5 pb-5">
      <h3>Completed ToDos</h3>
      <% @todos.each do |todo| %>
      <p><%= "#{todo.description} /  #{todo.completed}" %></p>
      <div class="card-columns">
        <div class="card text-center">
          <div class="card-body">
            <h5 class="card-text"><%= todo.description %></h5>
            <p class="card-text"><%= todo.completed %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-md-6 bg-white">
  <div class="d-md-flex align-items-center justify-content-center">
    <h3>Incompleted ToDos</h3>
    <% @todos.each do |todo| %>
    <p><%= "#{todo.description} /  #{todo.completed}" %></p>
      <div class="card-columns">
        <div class="card text-center">
          <div class="card-body">
            <h5 class="card-text"><%= todo.description %></h5>
            <p class="card-text"><%= todo.completed %></p>
          </div>
        </div>
      </div>
  </div>
</div>

</div>

<% end %>

app/views/todos/new.html.erb
<h1>Add a new ToDo below:</h1>

<%= render "form", todo: Todo.new %>

<%= link_to '<< Create a new "ToDo"', todos_new_path %>

app/views/todos/show.html.erb
<h1>Show ToDos</h1>

<p><%= "#{@todo.description} /  #{@todo.completed}" %></p>

<%= link_to '<< Back', todos_path %>